### ISSUE TITLE
tab-width setting just broke

### ISSUE THREAD

**Issue by jamesonquinn** [JuliaEditorSupport/atom-language-julia#112]
Symptoms:

Right after I updated language-julia (and some other packages), the editor no longer respects my tab width setting in .jl files; though I have it set to "2" (or any other number), tabs are width 4. The setting works in non-.jl files. This is true with various versions of atom (release and beta).

Packages currently installed (I've been trying to fix this for a little while, so this has changed a bit without fixing the bug):
ink@0.7.4
julia-client@0.6.0
language-julia@0.12.0
latex-completions@0.3.3
tab-control@0.6.10
tool-bar@1.1.0

Disabling language-julia fixes the problem.

**Comment by jamesonquinn** [comment]
If I manually check out version v0.11.0 of language-julia, the bug goes away.

**Comment by sglyon** [comment]
Hmm. Does it matter that you have quotes in that setting? Should it be just the integer `2`?

**Comment by jamesonquinn** [comment]
Hmm... git bisect tells me that the culprit is:

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[0393f57b5480ae0dd5c0aac6b8511607b7565510] set default tab length to 4 spaces (#95)

In other words, the true "bug" from my perspective is that language-julia doesn't just respect the global editor settings.

**Comment by jamesonquinn** [comment]
Hmm.... in order to get it to work with the latest checkout, I need to set the global setting to something other than 2, so that I can set the language-julia setting to 2 without it being considered "default" and thus interpreted as 4. Yuck.

**Comment by MikeInnes** [comment]
Yeah, this setting in language-julia overrides not just the global settings but also the user's language specific setting. I'm not a fan.

**Comment by sglyon** [comment]
That's odd. I would think that you should be able to go into the language-julia package settings on atom and set the tab length to 2.

Does this really not work if the global Atom setting is 2? If so that is something that needs to be changed in Atom b/c that's kinda ridiculous

**Comment by jamesonquinn** [comment]
Yes, really. If you try to set a subsidiary setting to be the same as the global setting it doesn't take because it's "already true". But in this case, it isn't.

**Comment by pfitzseb** [comment]
Yeah, I'm pretty sure this is an Atom bug, seems kinda similar to https://github.com/atom/settings-view/issues/774. Until that is resolved (will do some sleuthing tomorrow) I'd urge you to use indent-detective which should help in 99% of cases (the 1% being newly created files).

**Comment by sglyon** [comment]
I'm open to being convinced otherwise, but I disagree. 4 spaces is the recommended indentation for julia code, so to me it makes sense to have that as the default. 

To me, the first best outcome would be to "fix" (in my opinion) the issue in atom where the global editor setting  interacts at all with the language setting. I think the behavior should be to favor the user setting in the language, then the global setting for the user, then the default language setting, then the default global setting. You only move to the next level if all previous ones are undefined. 

Does that ordering make sense to others? I debated if the default language setting or the user global setting should be given precedence but opted for what I said so user settings are always given higher priority than default ones.

**Comment by jamesonquinn** [comment]
The problem is that Atom simply does not let you set a setting to the default. If you enter the default value, that just clears the setting. So "You only move to the next level if all previous ones are undefined" doesn't work as a plan.

**Comment by pfitzseb** [comment]
Alright, I'm pretty sure that bug has been fixed with https://github.com/atom/settings-view/pull/967, which should be included in one of the next Atom releases.

Until then you could either use indent-detective to auto detect tab width and to be able to conveniently change it per file, or add
```
".julia.source":
  editor:
    tabLength: 2
```
to your `config.cson`.

**Comment by sglyon** [comment]
Thanks for the responses here.

Hopefully the PR mentioned by @pfitzseb does indeed fix the issue here and all will be well.

Any idea on the ETA for the new Atom release?

**Comment by pfitzseb** [comment]
This seems to be fixed now on the Atom side.
