### ISSUE TITLE
Intalling the Julia Language package in atom

### ISSUE THREAD

**Issue by sandyirani** [JuliaEditorSupport/atom-language-julia#114]
I have been trying to install the Julia Language package in atom on my windows laptop. The download/install gets stalled at the same early stage every time. I did not experience this problem with the installation on either of my desktop computers. I don't believe that I have another Julia package installed on this machine.

Thank you.

**Comment by sglyon** [comment]
Hi @sandyirani thanks for opening the issue here.

Are you certain that this is an issue with the `atom-language-julia` package?

It is the first result in the list in the screenshot below:

<img width="601" alt="screen shot 2017-08-30 at 9 47 41 am" src="https://user-images.githubusercontent.com/1001948/29875538-56584262-8d68-11e7-967f-2746a6bc8062.png">
