### ISSUE TITLE
`Markdown.@md_str` breaks syntax highlighting

### ISSUE THREAD

**Issue by joshday** [JuliaEditorSupport/atom-language-julia#244]
Every other string macro I've tried is fine, but `md"text"` breaks the syntax highlighting for the rest of the document.

<img width="135" alt="Screen Shot 2021-06-15 at 10 05 29 AM" src="https://user-images.githubusercontent.com/8075494/122067019-38c8d480-cdc1-11eb-986e-58f556b28cdd.png">

**Comment by jeremiahpslewis** [comment]
This seems like it still is an issue and may need to be reopened, example here: https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FJuliaEditorSupport%2Fatom-language-julia%2Fblob%2Fmaster%2Fgrammars%2Fjulia.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FJuliaPluto%2FPlutoTest.jl%2Fblob%2Fmain%2Fsrc%2Fnotebook.jl&code=%3C%3Fphp%0D%0A%0D%0A%23%5BAttribute%5D%0D%0Aclass+Test+%7B%0D%0A%09function+__construct%28array+%24data%29+%7B%7D%0D%0A%7D%0D%0A%0D%0Afunction+method%28%23%5BTest%28%5B%27value%27+%3D%3E+true%5D%29%5D+%24data%29+%7B%7D+%2F%2F+%3C-----+here

**Comment by jeremiahpslewis** [comment]
(Ref: https://github.com/github/linguist/discussions/5637)

**Comment by pfitzseb** [comment]
Yeah, turns out I only committed the changelog entry in that PR. Should *actually* be fixed with https://github.com/JuliaEditorSupport/atom-language-julia/pull/252.

**Comment by jeremiahpslewis** [comment]
Hahaha, shame on me for believing the release notes ;) Can you tag a new version so I can annoy github about updating linguist?

**Comment by jeremiahpslewis** [comment]
PR is here for reference: https://github.com/github/linguist/pull/5638

**Comment by Alhadis** [comment]
**Pro-tip:** When embedding third-party grammars (particularly those you have no control over), it's always prudent to use a fixed-size pattern rather than a `begin`/`end` pair; i.e., this…

~~~cson
name: "string.quoted.double.julia"
match: '(")((?:[^"\\\\]|\\\\.)*+)(")'
captures:
	1: name: "punctuation.definition.string.begin.julia"
	2: name: "text.embedded.md", patterns: [include: "text.md"]
	3: name: "punctuation.definition.string.end.julia"
~~~

… instead of this:

~~~cson
name:  "string.quoted.double.julia"
begin: '"'
end:   '"'
beginCaptures: 0: name: "punctuation.definition.string.begin.julia"
endCaptures:   0: name: "punctuation.definition.string.end.julia"
contentName: "text.embedded.md"
patterns: [include: "text.md"]
~~~

I call this technique "clamping", because patterns that would otherwise threaten to spill past the `end` pattern (and ruin the document's highlighting) are confined to an existing capture group. The trade-off is that it isn't possible to embed multiline patterns this way, but that's a pretty sane trade-off when the alternative is screwing with the entire document.

**Comment by pfitzseb** [comment]
Thanks, that's a great solution. Do you have any ideas for multi-line strings, short of removing those rules?

**Comment by Alhadis** [comment]
> Do you have any ideas for multi-line strings, short of removing those rules?

[Yes](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_format=cson&grammar_url=&grammar_text=scopeName%3A+%22a%22%0D%0Apatterns%3A+%5B%0D%0A%09name%3A++%22string.quoted.double.julia%22%0D%0A%09begin%3A+%27%22%27%0D%0A%09end%3A+++%27%22%27%0D%0A%09beginCaptures%3A+0%3A+name%3A+%22punctuation.definition.string.begin.julia%22%0D%0A%09endCaptures%3A+++0%3A+name%3A+%22punctuation.definition.string.end.julia%22%0D%0A%09patterns%3A+%5B%7B%0D%0A%09%09name%3A+%22text.embedded.md%22%0D%0A%09%09match%3A+%27%28%3F%3A%5B%5E%22%5C%5C%5C%5C%5D%7C%5C%5C%5C%5C.%29*%2B%27%0D%0A%09%09captures%3A%0D%0A%09%09%090%3A+patterns%3A+%5Binclude%3A+%22source.gfm%22%5D%0D%0A%09%7D%5D%0D%0A%5D&code_source=from-text&code_url=&code=%22%23%23+Heading%0D%0A%3C%21--+Comment+%22+Not+a+comment+--%3E), though it's a little trickier:

~~~cson
name:  "string.quoted.double.julia"
begin: '"'
end:   '"'
beginCaptures: 0: name: "punctuation.definition.string.begin.julia"
endCaptures:   0: name: "punctuation.definition.string.end.julia"
patterns: [{
	name: "text.embedded.md"
	match: '(?:[^"\\\\]|\\\\.)*+'
	captures:
		0: patterns: [include: "text.md"]
}]
~~~
