### ISSUE TITLE
default tab should be 4 spaces?

### ISSUE THREAD

**Issue by ckingdon95** [JuliaEditorSupport/atom-language-julia#76]
The Julia style guide prefers 4 spaces, but currently the default tab spacing in atom is 2 spaces.

**Comment by MikeInnes** [comment]
I have seen this in the style guide for Base Julia, though not in any guide for all Julia code. Empirically, a significant minority of Julia packages use two spaces.

Anyway – we did originally do this but had to disable it. It caused confusion for those who wanted to customise it, since it streamrolls over the option in the Editor settings. A much nicer solution is [this plugin](https://github.com/JunoLab/atom-indent-detective) which will automatically set tab spacing for the current file.

**Comment by spencerlyon2** [comment]
Thanks @MikeInnes I was going to ping you here.

Is there not a way to override the setting from the grammar? That seems like a limitation in atom...

**Comment by davidanthoff** [comment]
I don't really understand what the problem is, but do we all agree that 4 spaces would be the right default for julia files?
